// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

// Был выбран вид репликации Master - Slave
// Тип - Eventual Consistency

// Шардирование будет происходить с помощью Key based

// Шардирование по Id
Table users {
  id integer [primary key]
  username varchar
  photo byte[]
  description varchar
  city varchar
  hobbies varchar
}

// Sharding by id
Table posts {
  id integer [primary key]
  owner_id integer
  description varchar
  media_id integer []
  hashtags varchar
  likes integer
  views integer
  comments varchar[]
}

// Sharding by id
Table chats {
  id integer [primary key]
}

// Sharding by id
Table messages {
  id integer [primary key]
  chat_id integer [primary key]
  user_id integer
  text text
  read bool
}

// Sharding by id
Table relationship {
  id integer [primary key]
  first_user_id integer 
  second_user_id integer
  status enum
}

Ref: "chats"."id" < "messages"."chat_id"

Ref: "users"."id" < "posts"."owner_id"

Ref: "users"."id" < "relationship"."first_user_id"

Ref: "users"."id" < "relationship"."second_user_id"

Ref: "users"."id" < "messages"."user_id"